site_name: express-sample-ag001801 documentation
nav:
  - Home: index.md
#   - 페이지명: example/md파일경로.md
  - Catalog yaml 작성 및 등록 가이드: pages/catalog-guide.md

docs_dir: idp/docs
plugins:
  - techdocs-core
markdown_extensions:
  - admonition  